<a href="https://colab.research.google.com/github/ashugoswami1501/data-science-lab-exp01/blob/main/Pandas_Dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd

In [2]:
data={'Name':['A','B','C','D'], 'AGE':[10,20,30,40], 'CITY':['L','M','N','O']}
student_df=DataFrame(data)

In [3]:
student_df

  Name  AGE CITY
0    A   10    L
1    B   20    M
2    C   30    N
3    D   40    O

In [4]:
student_df.columns

Index(['Name', 'AGE', 'CITY'], dtype='object')

In [5]:
student_df['Name']

0    A
1    B
2    C
3    D
Name: Name, dtype: object

In [6]:
student_df['AGE']

0    10
1    20
2    30
3    40
Name: AGE, dtype: int64

In [7]:
student=DataFrame(data=student_df, columns=['Name','CITY'])
student

  Name CITY
0    A    L
1    B    M
2    C    N
3    D    O

In [8]:
book_df=DataFrame({'Book':['A','B','C'],'Author':['D','E','F'],'PRICE':[100,200,300]})
book_df

  Book Author  PRICE
0    A      D    100
1    B      E    200
2    C      F    300

In [9]:
book_df['Publisher']='ABS'
book_df

  Book Author  PRICE Publisher
0    A      D    100       ABS
1    B      E    200       ABS
2    C      F    300       ABS

In [10]:
new_df=DataFrame()
new_df['serialNo']=np.arange(5)
new_df

   serialNo
0         0
1         1
2         2
3         3
4         4

In [11]:
movies_data={'movies':['A','B','C'],'Year':[2001,2002,2003],'Rating':[2,4,5]}
movie_df=DataFrame(movies_data)
movie_df

  movies  Year  Rating
0      A  2001       2
1      B  2002       4
2      C  2003       5

In [12]:
movie=DataFrame(data=movie_df, columns=['movies','Year','Director'])
movie

  movies  Year  Director
0      A  2001       NaN
1      B  2002       NaN
2      C  2003       NaN

In [13]:
s = pd.Series(['Delhi', 'Mumbai'], index=[0, 3])
s

0     Delhi
3    Mumbai
dtype: object

In [14]:
df = pd.DataFrame(index=range(4))
df['Branch'] = s
print(df)

   Branch
0   Delhi
1     NaN
2     NaN
3  Mumbai

In [16]:
employee_df = pd.DataFrame({
    'Employee': ['Aman', 'Riya', 'Rahul', 'Priya', 'Karan'],
    'Department': ['IT', 'HR', 'Sales', 'IT', 'Finance'],
    'Experience': [2, 4, 3, 5, 1]
})

new_df = employee_df[['Employee', 'Experience']]
print(new_df)

  Employee  Experience
0     Aman           2
1     Riya           4
2    Rahul           3
3    Priya           5
4    Karan           1

In [17]:
print(employee_df['Department'])
print(employee_df.columns)

0         IT
1         HR
2      Sales
3         IT
4    Finance
Name: Department, dtype: object
Index(['Employee', 'Department', 'Experience'], dtype='object')

In [18]:
employee_df['Office'] = 'Head Office'
print(employee_df)

  Employee Department  Experience       Office
0     Aman         IT           2  Head Office
1     Riya         HR           4  Head Office
2    Rahul      Sales           3  Head Office
3    Priya         IT           5  Head Office
4    Karan    Finance           1  Head Office

In [19]:
employee_df['Office'] = np.arange(5)
print(employee_df)

  Employee Department  Experience  Office
0     Aman         IT           2       0
1     Riya         HR           4       1
2    Rahul      Sales           3       2
3    Priya         IT           5       3
4    Karan    Finance           1       4

In [20]:
office_names = pd.Series(
    ['Delhi', 'Mumbai', 'Pune'],
    index=[0, 2, 4]
)

employee_df['Office'] = office_names
print(employee_df)

  Employee Department  Experience  Office
0     Aman         IT           2   Delhi
1     Riya         HR           4     NaN
2    Rahul      Sales           3  Mumbai
3    Priya         IT           5     NaN
4    Karan    Finance           1    Pune

In [21]:
employee_df.drop(columns=['Office'], inplace=True)
print(employee_df)

  Employee Department  Experience
0     Aman         IT           2
1     Riya         HR           4
2    Rahul      Sales           3
3    Priya         IT           5
4    Karan    Finance           1

In [22]:
product_df = pd.DataFrame({
    'Product': ['Laptop', 'Phone', 'Tablet'],
    'Category': ['Electronics', 'Electronics', 'Electronics'],
    'Price': [50000, 20000, 15000]
})

new_product_df = product_df[['Price', 'Product', 'Category']]
print(new_product_df)

   Price Product     Category
0  50000  Laptop  Electronics
1  20000   Phone  Electronics
2  15000  Tablet  Electronics

In [23]:
df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rahul'],
    'Age': [20, 21, 19],
    'City': ['Delhi', 'Mumbai', 'Pune']
})

new_df = df.reindex(columns=['Name', 'Age', 'City', 'Marks'])
print(new_df)

    Name  Age    City  Marks
0   Aman   20   Delhi    NaN
1   Riya   21  Mumbai    NaN
2  Rahul   19    Pune    NaN

In [24]:
marks_df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rahul'],
    'Total Marks': [85, 92, 78]
})

print(marks_df['Total Marks'])

0    85
1    92
2    78
Name: Total Marks, dtype: int64

In [25]:
course_df = pd.DataFrame({
    'Student': ['Aman', 'Riya', 'Rahul', 'Priya', 'Karan'],
    'Course': ['DS', 'Java', 'Python', 'DBMS', 'DSA'],
    'Score': [85, 90, 78, 88, 92]
})

print(course_df.columns)

print(course_df['Student'])

new_df = course_df[['Student', 'Score']]
print(new_df)

course_df['Batch'] = '2026'
print(course_df)

Index(['Student', 'Course', 'Score'], dtype='object')
0     Aman
1     Riya
2    Rahul
3    Priya
4    Karan
Name: Student, dtype: object
  Student  Score
0    Aman     85
1    Riya     90
2   Rahul     78
3   Priya     88
4   Karan     92
  Student  Course  Score Batch
0    Aman      DS     85  2026
1    Riya    Java     90  2026
2   Rahul  Python     78  2026
3   Priya    DBMS     88  2026
4   Karan     DSA     92  2026

In [27]:
travel_df = pd.DataFrame({
    'Place': ['Delhi', 'Mumbai', 'Pune', 'Agra', 'Jaipur']
})

travel_df['Code'] = np.arange(5)
print(travel_df)

code_series = pd.Series(['A1', 'A4'], index=[1, 4])

travel_df['Code'] = code_series
print(travel_df)

    Place  Code
0   Delhi     0
1  Mumbai     1
2    Pune     2
3    Agra     3
4  Jaipur     4
    Place Code
0   Delhi  NaN
1  Mumbai   A1
2    Pune  NaN
3    Agra  NaN
4  Jaipur   A4

In [28]:
school_df = pd.DataFrame({
    'Student': ['Aman', 'Riya', 'Rahul', 'Priya', 'Karan'],
    'Class': [10, 10, 12, 11, 12],
    'Section': ['A', 'B', 'A', 'C', 'B']
})

new_df = school_df.reindex(
    columns=['Student', 'Class', 'Section', 'House']
)

print(new_df)

new_df['House'] = 'Blue'
print(new_df)

  Student  Class Section  House
0    Aman     10       A    NaN
1    Riya     10       B    NaN
2   Rahul     12       A    NaN
3   Priya     11       C    NaN
4   Karan     12       B    NaN
  Student  Class Section House
0    Aman     10       A  Blue
1    Riya     10       B  Blue
2   Rahul     12       A  Blue
3   Priya     11       C  Blue
4   Karan     12       B  Blue

In [31]:
inventory_df = pd.DataFrame({
    'Item': ['Pen', 'Book', 'Bag', 'Pencil', 'Eraser'],
    'Quantity': [10, 20, 5, 15, 8],
    'Price': [10, 50, 500, 5, 3]
})

print(inventory_df)

stock = pd.Series(
    [100, 200, 300],
    index=[0, 2, 4]
)

inventory_df['Stock'] = stock
print(inventory_df)

inventory_df.drop(columns=['Stock'], inplace=True)
print(inventory_df)

     Item  Quantity  Price
0     Pen        10     10
1    Book        20     50
2     Bag         5    500
3  Pencil        15      5
4  Eraser         8      3
     Item  Quantity  Price  Stock
0     Pen        10     10  100.0
1    Book        20     50    NaN
2     Bag         5    500  200.0
3  Pencil        15      5    NaN
4  Eraser         8      3  300.0
     Item  Quantity  Price
0     Pen        10     10
1    Book        20     50
2     Bag         5    500
3  Pencil        15      5
4  Eraser         8      3