<a href="https://colab.research.google.com/github/ashugoswami1501/Data_Science/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
from pandas import Series,DataFrame
import pandas as pd

In [11]:
arr=np.arange(11,30,2)
print(arr)
print(arr.ndim)
print(arr.size)

[11 13 15 17 19 21 23 25 27 29]
1
10

In [12]:
np.linspace(5,35,7)

array([ 5., 10., 15., 20., 25., 30., 35.])

In [13]:
arrr=np.arange(12).reshape(4,3)
arrr.fill(9)
arrr

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [14]:
a=np.array([6,12,18,24])
a%5

array([1, 2, 3, 4])

In [15]:
arr1=[14, 28, 42, 56, 70, 84]
arr1[1:6:2]

[28, 56, 84]

In [16]:
b=np.array([-16, 25, -36, 49])
c=np.abs(b)
print(c)
np.sqrt(c)

[16 25 36 49]

array([4., 5., 6., 7.])

In [17]:
print(np.arange(7,13).reshape(3,2))
print(arr.shape)
print(arr.T)
print(arr.T.shape)

[[ 7  8]
 [ 9 10]
 [11 12]]
(10,)
[11 13 15 17 19 21 23 25 27 29]
(10,)

In [18]:
temp = np.array([18, 22, 27, 31, 24, 19])
print(np.max(temp)-np.min(temp))
print(np.median(temp))

13
23.0

In [19]:
values = np.array([4, 9, 4, 2, 9, 7, 2, 4])
np.unique(values)

array([2, 4, 7, 9])

In [20]:
speed = np.array([35, 62, 48, 81, 55])
speeed=np.where(speed>=60)
speeed

(array([1, 3]),)

Pandas

In [21]:
books=Series([24, 31, 19, 27],index=['Monday', 'Tuesday', 'Wednesday','Thursday'])
books

Monday       24
Tuesday      31
Wednesday    19
Thursday     27
dtype: int64

In [22]:
devices=Series([45000, 18000, 22000],index=['Laptop', 'Tablet', 'Phone'])
devices['Tablet']

np.int64(18000)

In [23]:
rainfall = pd.Series([12, 0, 18, 5, 23])
rainfall[rainfall>10]

0    12
2    18
4    23
dtype: int64

In [24]:
rate={'Gold': 7200, 'Silver': 95, 'Copper': 850}
series=Series(rate)
series

Gold      7200
Silver      95
Copper     850
dtype: int64

In [25]:
rating=Series([3.5, 4.2, 2.8, 4.7])
rating.name='Customer Rating'
rating.index.name='review id'
rating

review id
0    3.5
1    4.2
2    2.8
3    4.7
Name: Customer Rating, dtype: float64

In [26]:
s = Series([11, 22, 33], index=['X1', 'X2', 'X3'])
if('X4' in s):
  print("true")
else:
  print("false")

false

In [29]:
stock = pd.Series([16, 28, 12],
index=['Keyboard', 'Mouse', 'Monitor'])
stk=stock.to_dict()
stk

{'Keyboard': 16, 'Mouse': 28, 'Monitor': 12}

In [30]:
book={'Hindi': 78, 'English': 84, 'Computer': 91}
boook=Series(book)
boook

Hindi       78
English     84
Computer    91
dtype: int64

In [33]:
expenses = pd.Series([1200, None, 850, None, 600])
print(expenses.isnull())
print(expenses.notnull())

0    False
1     True
2    False
3     True
4    False
dtype: bool
0     True
1    False
2     True
3    False
4     True
dtype: bool

In [34]:
a = pd.Series([8, 15, 22], index=['P', 'Q', 'R'])
b = pd.Series([4, 6, 10], index=['R', 'P', 'Q'])
print(a + b)

P    14
Q    25
R    26
dtype: int64

In [49]:
sales = np.array([
    [120, 150, 180],
    [140, 160, 175],
    [135, 155, 190],
    [150, 170, 200]
])
print(np.sum(sales, axis=1))
print(np.sum(sales, axis=0))
daily_total = np.sum(sales, axis=1)
print(np.argmax(daily_total) + 1)

[450 475 480 520]
[545 635 745]
4

In [50]:
arr = np.arange(10, 46).reshape(6, 6)
print(arr)
sub = arr[2:6, 1:5]
print(sub)
print(np.mean(sub))

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]
 [40 41 42 43 44 45]]
[[23 24 25 26]
 [29 30 31 32]
 [35 36 37 38]
 [41 42 43 44]]
33.5

In [51]:
weights = np.array([48, 62, 75, 81, 54, 69, 90])
print(weights[weights > 70])
new_weights = np.where(weights < 55, 55, weights)
print(new_weights)
print(weights)

[75 81 90]
[55 62 75 81 55 69 90]
[48 62 75 81 54 69 90]

In [38]:
quantity = np.array([3, 5, 2, 7])
price = np.array([120, 80, 250, 60])
cost = quantity * price
total_bill = np.sum(cost)
percentage = (cost / total_bill) * 100
print(cost)
print(total_bill)
print(percentage)

Product costs: [360 400 500 420]
Total bill: 1680
Percentage contribution: [21.42857143 23.80952381 29.76190476 25.        ]

In [39]:
arr = np.array([[10, 20, 30, 40],[15, 25, 35, 45],[20, 30, 40, 50]])
print(np.var(arr, axis=1))
print(np.std(arr, axis=1))
print(np.var(arr, axis=0))
print(np.std(arr, axis=0))

Row variance: [125. 125. 125.]
Row standard deviation: [11.18033989 11.18033989 11.18033989]
Column variance: [16.66666667 16.66666667 16.66666667 16.66666667]
Column standard deviation: [4.0824829 4.0824829 4.0824829 4.0824829]

In [40]:
A = np.array([[1, 2, 3],[4, 5, 6]])
B = np.array([[1, 2],[3, 4],[5, 6]])
print(np.dot(A, B))

Matrix multiplication:
 [[22 28]
 [49 64]]

In [41]:
arr = np.random.randint(10, 100, 25)
print(arr)
sorted_arr = np.sort(arr)
print(sorted_arr)
print(sorted_arr[-5:][::-1])
print(len(np.unique(arr)))

Random integers: [63 48 56 50 30 88 12 21 55 21 55 90 95 38 51 43 71 90 19 79 72 98 76 62
 87]
Sorted array: [12 19 21 21 30 38 43 48 50 51 55 55 56 62 63 71 72 76 79 87 88 90 90 95
 98]
Five largest values: [98 95 90 90 88]
Number of unique observations: 22

In [42]:
a = np.array([5, 10, 15, 20, 25, 30])
b = a[1:5]
c = a[1:5].copy()
b[1] = 99
c[2] = 77
print(a)
print(b)
print(c)

a = [ 5 10 99 20 25 30]
b = [10 99 20 25]
c = [10 15 77 25]

In [43]:
dept_a = pd.Series({'Jan': 250, 'Feb': 310, 'Mar': 290})
dept_b = pd.Series({'Mar': 180, 'Jan': 210, 'Apr': 260})
result = dept_a + dept_b
print(result)
print(result[result.isnull()])

Apr      NaN
Feb      NaN
Jan    460.0
Mar    470.0
dtype: float64
Missing values:
 Apr   NaN
Feb   NaN
dtype: float64

In [44]:
attendance = pd.Series([82, 67, 91, 74, 58],index=['S101', 'S102', 'S103', 'S104', 'S105'])
low = attendance[attendance < 75]
print(low)
print(len(low))

Students below 75%:
S102    67
S104    74
S105    58
dtype: int64
Count: 3

In [45]:
inventory = {'Pen': 50,'Pencil': 80,'Eraser': 40,'Scale': 25}
labels = ['Scale', 'Pen', 'Marker', 'Eraser']
s = pd.Series(inventory, index=labels)
print(s)

Scale     25.0
Pen       50.0
Marker     NaN
Eraser    40.0
dtype: float64

In [46]:
s1 = pd.Series([100, 200, 300],index=['North', 'South', 'East'])
s2 = pd.Series(
    [10, 20, 30],
    index=['South', 'West', 'North']
)
result = s1 - s2
print(result)
print(result.notnull())

East       NaN
North     70.0
South    190.0
West       NaN
dtype: float64
Non-missing entries:
East     False
North     True
South     True
West     False
dtype: bool

In [47]:
consumption = pd.Series([180, 320, 270, 240, 400],index=['H1', 'H2', 'H3', 'H4', 'H5'])
filtered = consumption[consumption > 250]
print(filtered)
data = filtered.to_dict()
print(data)
new_series = pd.Series(data)
print(new_series)

Filtered Series:
H2    320
H3    270
H5    400
dtype: int64
Dictionary: {'H2': 320, 'H3': 270, 'H5': 400}
New Series:
H2    320
H3    270
H5    400
dtype: int64